#!/bin/sh

set -eu

ROOT="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"

sh "$ROOT/run_qmk_contract_checks.sh"
sh "$ROOT/run_keyboard_mod_ownership_tests.sh"
sh "$ROOT/run_owned_keycode_tests.sh"
sh "$ROOT/run_held_action_tests.sh"
sh "$ROOT/run_layer_ownership_tests.sh"
sh "$ROOT/run_pd_mode_tests.sh"
sh "$ROOT/run_pd_mode_handlers_tests.sh"
sh "$ROOT/run_pointer_layer_policy_tests.sh"
sh "$ROOT/run_split_runtime_sync_tests.sh"
sh "$ROOT/run_key_behavior_lookup_tests.sh"
sh "$ROOT/run_key_behavior_validation_tests.sh"
sh "$ROOT/run_keymap_validation_tests.sh"
sh "$ROOT/run_real_profile_validation_tests.sh"
sh "$ROOT/run_pd_mode_key_runtime_integration_tests.sh"
sh "$ROOT/run_action_lifecycle_tests.sh"
sh "$ROOT/run_macro_payload_tests.sh"
sh "$ROOT/run_via_macro_action_lifecycle_tests.sh"
sh "$ROOT/run_key_runtime_feedback_tests.sh"
sh "$ROOT/run_key_runtime_preflight_tests.sh"
sh "$ROOT/run_key_runtime_transition_tests.sh"
sh "$ROOT/run_key_runtime_modifier_hold_integration_tests.sh"
sh "$ROOT/run_feature_gate_compile_tests.sh"
sh "$ROOT/run_rgb_validation_tests.sh"
sh "$ROOT/run_rgb_layer_render_tests.sh"
