// Compiled factory slot defaults. These values are encoded into the effective
// eight-slot cache when the firmware has no live profile owner.
#pragma once

#ifndef VOLUME_THRESHOLD
#    define VOLUME_THRESHOLD 60
#endif
#ifndef BRIGHTNESS_THRESHOLD
#    define BRIGHTNESS_THRESHOLD 60
#endif
#ifndef ZOOM_THRESHOLD
#    define ZOOM_THRESHOLD 80
#endif
#ifndef ARROW_THRESHOLD_X
#    define ARROW_THRESHOLD_X 40
#endif
#ifndef ARROW_THRESHOLD_Y
#    define ARROW_THRESHOLD_Y 50
#endif
#ifndef NOAH_DRAGSCROLL_THRESHOLD_H
#    define NOAH_DRAGSCROLL_THRESHOLD_H 6
#endif
#ifndef NOAH_DRAGSCROLL_THRESHOLD_V
#    define NOAH_DRAGSCROLL_THRESHOLD_V 6
#endif
#ifndef NOAH_DRAGSCROLL_DIVISOR_H
#    define NOAH_DRAGSCROLL_DIVISOR_H 8
#endif
#ifndef NOAH_DRAGSCROLL_DIVISOR_V
#    define NOAH_DRAGSCROLL_DIVISOR_V 8
#endif
#ifndef NOAH_DRAGSCROLL_RATE_LIMIT_MS
#    define NOAH_DRAGSCROLL_RATE_LIMIT_MS 16
#endif
#ifndef NOAH_DRAGSCROLL_BUFFER_EXPIRE_MS
#    define NOAH_DRAGSCROLL_BUFFER_EXPIRE_MS 100
#endif
#ifndef NOAH_DRAGSCROLL_LOCK_START_RATIO_NUM
#    define NOAH_DRAGSCROLL_LOCK_START_RATIO_NUM 3
#endif
#ifndef NOAH_DRAGSCROLL_LOCK_START_RATIO_DEN
#    define NOAH_DRAGSCROLL_LOCK_START_RATIO_DEN 1
#endif
#ifndef NOAH_DRAGSCROLL_LOCK_SUSTAIN_RATIO_NUM
#    define NOAH_DRAGSCROLL_LOCK_SUSTAIN_RATIO_NUM 3
#endif
#ifndef NOAH_DRAGSCROLL_LOCK_SUSTAIN_RATIO_DEN
#    define NOAH_DRAGSCROLL_LOCK_SUSTAIN_RATIO_DEN 1
#endif
#ifndef NOAH_DRAGSCROLL_LOCK_TIMEOUT_MS
#    define NOAH_DRAGSCROLL_LOCK_TIMEOUT_MS 40
#endif
#ifndef NOAH_DRAGSCROLL_CROSS_AXIS_DECAY_DIVISOR
#    define NOAH_DRAGSCROLL_CROSS_AXIS_DECAY_DIVISOR 2
#endif
#ifndef PD_MODE_VOLUME_DPI
#    define PD_MODE_VOLUME_DPI 0
#endif
#ifndef PD_MODE_BRIGHTNESS_DPI
#    define PD_MODE_BRIGHTNESS_DPI 0
#endif
#ifndef PD_MODE_ZOOM_DPI
#    define PD_MODE_ZOOM_DPI 0
#endif
#ifndef PD_MODE_ARROW_DPI
#    define PD_MODE_ARROW_DPI 0
#endif
#ifndef CHARYBDIS_DRAGSCROLL_DPI
#    define CHARYBDIS_DRAGSCROLL_DPI 100
#endif
