// {{PROFILE_TITLE}} Charybdis 4x6 profile configuration.
#pragma once

#ifndef __ASSEMBLER__
enum charybdis_keymap_layers {
    LAYER_BASE = 0,
    LAYER_NUM,
    LAYER_SYM,
    LAYER_NAV,
    LAYER_POINTER,
    LAYER_COUNT,
};
#endif

#define TAPPING_TERM 200
#define COMBO_TERM 50

#define KEY_BEHAVIOR_MAX_TAP_COUNT 5
#define CUSTOM_TAP_HOLD_TERM 150
#define CUSTOM_LONGER_HOLD_TERM 400
#define CUSTOM_MULTI_TAP_TERM 150
#define CUSTOM_RGB_BRANCH_CONFIRM_TERM 150

#ifdef POINTING_DEVICE_ENABLE

#    define CHARYBDIS_DRAGSCROLL_DPI 100

#    define PD_MODE_VOLUME_DPI 0
#    define PD_MODE_BRIGHTNESS_DPI 0
#    define PD_MODE_ZOOM_DPI 400
#    define PD_MODE_ARROW_DPI 400

#    define CHARYBDIS_MINIMUM_DEFAULT_DPI 400
#    define CHARYBDIS_DEFAULT_DPI_CONFIG_STEP 200

#    define CHARYBDIS_MINIMUM_SNIPING_DPI 100
#    define CHARYBDIS_SNIPING_DPI_CONFIG_STEP 100

#    define CHARYBDIS_AUTO_SNIPING_ENABLE
#    define CHARYBDIS_AUTO_SNIPING_LAYER LAYER_NAV

#    define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#    define AUTO_MOUSE_DEFAULT_LAYER LAYER_POINTER
#    define AUTO_MOUSE_TIME 1200

#endif // POINTING_DEVICE_ENABLE

#ifdef RGB_MATRIX_ENABLE

#    define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_COLOR
#    define RGB_MATRIX_DEFAULT_HUE 0
#    define RGB_MATRIX_DEFAULT_SAT 255
#    define RGB_MATRIX_MAXIMUM_BRIGHTNESS 200
#    undef RGB_MATRIX_DEFAULT_VAL
#    define RGB_MATRIX_DEFAULT_VAL RGB_MATRIX_MAXIMUM_BRIGHTNESS
#    define RGB_MATRIX_LED_FLUSH_LIMIT 32
#    define RGB_MATRIX_TIMEOUT 900000

#    ifdef POINTING_DEVICE_ENABLE
#        define RGB_PD_MODE_FEEDBACK_ENABLE
#    endif

#    ifdef COMBO_ENABLE
#        define RGB_COMBO_FEEDBACK_ENABLE
#    endif

#    define RGB_KEY_BEHAVIOR_FEEDBACK_ENABLE
#    define RGB_KEY_BEHAVIOR_FEEDBACK_FLASH_HALF_PERIOD_MS 200

#    ifdef POINTING_DEVICE_AUTO_MOUSE_ENABLE
#        define RGB_AUTOMOUSE_GRADIENT_ENABLE
#        define AUTOMOUSE_RGB_DEAD_TIME (AUTO_MOUSE_TIME / 3)
#    endif

#endif // RGB_MATRIX_ENABLE
