#pragma once

#include "noah_compile_config.h"

#ifdef RGB_PD_MODE_FEEDBACK_ENABLE
#    undef RGB_PD_MODE_FEEDBACK_ENABLE
#endif

#ifdef RGB_COMBO_FEEDBACK_ENABLE
#    undef RGB_COMBO_FEEDBACK_ENABLE
#endif

#ifdef RGB_KEY_BEHAVIOR_FEEDBACK_ENABLE
#    undef RGB_KEY_BEHAVIOR_FEEDBACK_ENABLE
#endif

#ifdef RGB_KEY_BEHAVIOR_FEEDBACK_FLASH_HALF_PERIOD_MS
#    undef RGB_KEY_BEHAVIOR_FEEDBACK_FLASH_HALF_PERIOD_MS
#endif

#ifdef RGB_AUTOMOUSE_GRADIENT_ENABLE
#    undef RGB_AUTOMOUSE_GRADIENT_ENABLE
#endif

#ifdef AUTOMOUSE_RGB_DEAD_TIME
#    undef AUTOMOUSE_RGB_DEAD_TIME
#endif
