#!/usr/bin/env python3
"""Generate a diffable authored-profile summary from keymap source data."""

from __future__ import annotations

import argparse
import ast
import colorsys
import difflib
import json
import re
import sys
from dataclasses import asdict, dataclass
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent

KEYMAP_FILE = REPO_ROOT / "keyboards" / "bastardkb" / "charybdis" / "4x6" / "keymaps" / "noah" / "keymap.c"
CONFIG_FILE = REPO_ROOT / "keyboards" / "bastardkb" / "charybdis" / "4x6" / "keymaps" / "noah" / "config.h"
RGB_CONFIG_FILE = REPO_ROOT / "keyboards" / "bastardkb" / "charybdis" / "4x6" / "keymaps" / "noah" / "rgb_config.c"
NOAH_KEYMAP_IDS_FILE = REPO_ROOT / "users" / "noah" / "noah_keymap_ids.h"
PD_MODE_MANIFEST_FILE = REPO_ROOT / "users" / "noah" / "lib" / "pointing" / "defs" / "pd_mode_manifest.h"

OUTPUT_DIR = REPO_ROOT / "docs" / "generated"
MARKDOWN_OUTPUT = OUTPUT_DIR / "profile-introspection.md"
JSON_OUTPUT = OUTPUT_DIR / "profile-summary.json"
LAYER_IMAGE_PREFIX = "profile-layer-"

MARKDOWN_HEADER = "<!-- Generated by tools/profile_introspect.py. Do not edit by hand. -->\n"

CONFIG_MACROS = [
    "TAPPING_TERM",
    "COMBO_TERM",
    "KEY_BEHAVIOR_MAX_TAP_COUNT",
    "CUSTOM_TAP_HOLD_TERM",
    "CUSTOM_LONGER_HOLD_TERM",
    "CUSTOM_MULTI_TAP_TERM",
    "CHARYBDIS_DRAGSCROLL_DPI",
    "PD_MODE_VOLUME_DPI",
    "PD_MODE_BRIGHTNESS_DPI",
    "PD_MODE_ZOOM_DPI",
    "PD_MODE_ARROW_DPI",
    "CHARYBDIS_MINIMUM_DEFAULT_DPI",
    "CHARYBDIS_DEFAULT_DPI_CONFIG_STEP",
    "CHARYBDIS_MINIMUM_SNIPING_DPI",
    "CHARYBDIS_SNIPING_DPI_CONFIG_STEP",
    "CHARYBDIS_AUTO_SNIPING_LAYER",
    "AUTO_MOUSE_DEFAULT_LAYER",
    "AUTO_MOUSE_TIME",
    "RGB_MATRIX_DEFAULT_MODE",
    "RGB_MATRIX_DEFAULT_HUE",
    "RGB_MATRIX_DEFAULT_SAT",
    "RGB_MATRIX_MAXIMUM_BRIGHTNESS",
    "RGB_MATRIX_DEFAULT_VAL",
    "RGB_MATRIX_LED_FLUSH_LIMIT",
    "RGB_MATRIX_TIMEOUT",
    "RGB_KEY_BEHAVIOR_FEEDBACK_FLASH_HALF_PERIOD_MS",
    "AUTOMOUSE_RGB_DEAD_TIME",
]

_PD_MODE_MANIFEST_ENTRY_PATTERN = re.compile(r"^\s*PDM\(\s*([A-Z_][A-Z0-9_]*)\s*,\s*([A-Z_][A-Z0-9_]*)\s*,")

# Derived from the upstream Charybdis 4x6 keyboard.json LAYOUT definition.
LAYOUT_TEMPLATE = [
    {"matrix": [0, 0], "x": 0, "y": 0},
    {"matrix": [0, 1], "x": 1, "y": 0},
    {"matrix": [0, 2], "x": 2, "y": 0},
    {"matrix": [0, 3], "x": 3, "y": 0},
    {"matrix": [0, 4], "x": 4, "y": 0},
    {"matrix": [0, 5], "x": 5, "y": 0},
    {"matrix": [5, 5], "x": 11, "y": 0},
    {"matrix": [5, 4], "x": 12, "y": 0},
    {"matrix": [5, 3], "x": 13, "y": 0},
    {"matrix": [5, 2], "x": 14, "y": 0},
    {"matrix": [5, 1], "x": 15, "y": 0},
    {"matrix": [5, 0], "x": 16, "y": 0},
    {"matrix": [1, 0], "x": 0, "y": 1},
    {"matrix": [1, 1], "x": 1, "y": 1},
    {"matrix": [1, 2], "x": 2, "y": 1},
    {"matrix": [1, 3], "x": 3, "y": 1},
    {"matrix": [1, 4], "x": 4, "y": 1},
    {"matrix": [1, 5], "x": 5, "y": 1},
    {"matrix": [6, 5], "x": 11, "y": 1},
    {"matrix": [6, 4], "x": 12, "y": 1},
    {"matrix": [6, 3], "x": 13, "y": 1},
    {"matrix": [6, 2], "x": 14, "y": 1},
    {"matrix": [6, 1], "x": 15, "y": 1},
    {"matrix": [6, 0], "x": 16, "y": 1},
    {"matrix": [2, 0], "x": 0, "y": 2},
    {"matrix": [2, 1], "x": 1, "y": 2},
    {"matrix": [2, 2], "x": 2, "y": 2},
    {"matrix": [2, 3], "x": 3, "y": 2},
    {"matrix": [2, 4], "x": 4, "y": 2},
    {"matrix": [2, 5], "x": 5, "y": 2},
    {"matrix": [7, 5], "x": 11, "y": 2},
    {"matrix": [7, 4], "x": 12, "y": 2},
    {"matrix": [7, 3], "x": 13, "y": 2},
    {"matrix": [7, 2], "x": 14, "y": 2},
    {"matrix": [7, 1], "x": 15, "y": 2},
    {"matrix": [7, 0], "x": 16, "y": 2},
    {"matrix": [3, 0], "x": 0, "y": 3},
    {"matrix": [3, 1], "x": 1, "y": 3},
    {"matrix": [3, 2], "x": 2, "y": 3},
    {"matrix": [3, 3], "x": 3, "y": 3},
    {"matrix": [3, 4], "x": 4, "y": 3},
    {"matrix": [3, 5], "x": 5, "y": 3},
    {"matrix": [8, 5], "x": 11, "y": 3},
    {"matrix": [8, 4], "x": 12, "y": 3},
    {"matrix": [8, 3], "x": 13, "y": 3},
    {"matrix": [8, 2], "x": 14, "y": 3},
    {"matrix": [8, 1], "x": 15, "y": 3},
    {"matrix": [8, 0], "x": 16, "y": 3},
    {"matrix": [4, 3], "x": 5, "y": 4},
    {"matrix": [4, 4], "x": 6, "y": 4},
    {"matrix": [4, 1], "x": 7, "y": 4},
    {"matrix": [9, 1], "x": 9, "y": 4},
    {"matrix": [9, 3], "x": 10, "y": 4},
    {"matrix": [4, 5], "x": 6, "y": 5},
    {"matrix": [4, 2], "x": 7, "y": 5},
    {"matrix": [9, 5], "x": 9, "y": 5},
]

DISPLAY_ALIASES = {
    "KC_ESCAPE": "ESC",
    "KC_ESC": "ESC",
    "KC_ENTER": "ENT",
    "KC_ENT": "ENT",
    "KC_SPACE": "SPC",
    "KC_SPC": "SPC",
    "KC_BACKSPACE": "BSPC",
    "KC_BSPC": "BSPC",
    "KC_DELETE": "DEL",
    "KC_DEL": "DEL",
    "KC_TAB": "TAB",
    "KC_LEFT_SHIFT": "LSFT",
    "KC_RIGHT_SHIFT": "RSFT",
    "KC_LEFT_CTRL": "LCTL",
    "KC_RIGHT_CTRL": "RCTL",
    "KC_LEFT_ALT": "LALT",
    "KC_RIGHT_ALT": "RALT",
    "KC_LEFT_GUI": "LGUI",
    "KC_RIGHT_GUI": "RGUI",
    "KC_LEFT": "LEFT",
    "KC_RIGHT": "RIGHT",
    "KC_UP": "UP",
    "KC_DOWN": "DOWN",
    "KC_MPLY": "PLAY",
    "KC_MNXT": "NEXT",
    "KC_MPRV": "PREV",
    "KC_MUTE": "MUTE",
    "KC_VOLD": "VOL-",
    "KC_VOLU": "VOL+",
    "KC_BRID": "BRI-",
    "KC_BRIU": "BRI+",
    "KC_COMM": ",",
    "KC_DOT": ".",
    "KC_SLSH": "/",
    "KC_BSLS": "\\",
    "KC_SCLN": ";",
    "KC_QUOT": "'",
    "KC_MINS": "-",
    "KC_UNDS": "_",
    "KC_LBRC": "[",
    "KC_RBRC": "]",
    "KC_LCBR": "{",
    "KC_RCBR": "}",
    "KC_LABK": "<",
    "KC_RABK": ">",
    "KC_COLN": ":",
    "KC_PIPE": "|",
    "KC_DQUO": '"',
    "KC_PEQL": "=",
    "KC_PPLS": "P+",
    "KC_PMNS": "P-",
    "KC_PAST": "P*",
    "KC_PSLS": "P/",
    "KC_PDOT": "P.",
    "_______": "TRNS",
    "XXXXXXX": "NO",
    "LEFT_THUMB": "LTHUMB",
    "RIGHT_THUMB": "RTHUMB",
    "KC_RGHT": "RIGHT",
}

TAP_COUNT_NAMES = {
    0: "single",
    1: "double",
    2: "triple",
    3: "quadruple",
    4: "quintuple",
}

SVG_BACKGROUND = "#2f2f2f"
SVG_CANVAS_WIDTH = 1120
SVG_CANVAS_HEIGHT = 620
KEY_WIDTH = 58
KEY_HEIGHT = 58
KEY_RADIUS = 7
KEYBOARD_Y_OFFSET = 54
TITLE_X = 32
TITLE_Y = 40
SUBTITLE_Y = 68
LEFT_COLUMN_X = [36, 102, 168, 234, 300, 366]
LEFT_COLUMN_TOP_Y = [118, 118, 78, 54, 78, 78]
RIGHT_COLUMN_X = [698, 764, 830, 896, 962, 1028]
RIGHT_COLUMN_TOP_Y = [78, 78, 54, 78, 118, 118]
ROW_Y_STEP = 64
THUMB_VISUALS = {
    48: {"x": 328, "y": 354, "angle": 0},
    49: {"x": 396, "y": 350, "angle": 10},
    50: {"x": 468, "y": 358, "angle": 17},
    51: {"x": 576, "y": 358, "angle": -17},
    52: {"x": 648, "y": 350, "angle": -10},
    53: {"x": 398, "y": 432, "angle": 9},
    54: {"x": 468, "y": 446, "angle": 15},
    55: {"x": 578, "y": 432, "angle": -15},
}


@dataclass
class BehaviorAction:
    helper: str
    action: str
    repeat_hz: int | None = None


@dataclass
class BehaviorStep:
    tap_count: int
    tap: BehaviorAction | None = None
    hold: BehaviorAction | None = None
    long_hold: BehaviorAction | None = None


@dataclass
class KeyBehavior:
    keycode: str
    tap_hold_term: int | None
    longer_hold_term: int | None
    multi_tap_term: int | None
    steps: list[BehaviorStep]


@dataclass
class MacroSlot:
    kind: str
    slot: int
    keycode: str
    payload: str
    empty: bool


@dataclass
class Combo:
    output: str
    inputs: list[str]


def die(message: str) -> "NoReturn":
    raise SystemExit(message)


def read_text(path: Path) -> str:
    if not path.exists():
        die(f"missing required file: {path}")
    return path.read_text()


def strip_comments(text: str) -> str:
    result: list[str] = []
    i = 0
    quote: str | None = None

    while i < len(text):
        ch = text[i]
        nxt = text[i + 1] if i + 1 < len(text) else ""

        if quote is not None:
            result.append(ch)
            if ch == "\\" and i + 1 < len(text):
                result.append(text[i + 1])
                i += 2
                continue
            if ch == quote:
                quote = None
            i += 1
            continue

        if ch in {'"', "'"}:
            quote = ch
            result.append(ch)
            i += 1
            continue

        if ch == "/" and nxt == "/":
            i += 2
            while i < len(text) and text[i] != "\n":
                i += 1
            continue

        if ch == "/" and nxt == "*":
            i += 2
            while i + 1 < len(text) and (text[i] != "*" or text[i + 1] != "/"):
                i += 1
            i += 2
            continue

        result.append(ch)
        i += 1

    return "".join(result)


def normalize_expr(text: str) -> str:
    text = text.strip()
    if not text:
        return text

    result: list[str] = []
    i = 0
    quote: str | None = None

    while i < len(text):
        ch = text[i]

        if quote is not None:
            result.append(ch)
            if ch == "\\" and i + 1 < len(text):
                result.append(text[i + 1])
                i += 2
                continue
            if ch == quote:
                quote = None
            i += 1
            continue

        if ch in {'"', "'"}:
            quote = ch
            result.append(ch)
            i += 1
            continue

        if ch.isspace():
            i += 1
            continue

        result.append(ch)
        i += 1

    return "".join(result)


def find_matching(text: str, start_index: int, open_char: str, close_char: str) -> int:
    depth = 0
    quote: str | None = None
    i = start_index

    while i < len(text):
        ch = text[i]

        if quote is not None:
            if ch == "\\":
                i += 2
                continue
            if ch == quote:
                quote = None
            i += 1
            continue

        if ch in {'"', "'"}:
            quote = ch
            i += 1
            continue

        if ch == open_char:
            depth += 1
        elif ch == close_char:
            depth -= 1
            if depth == 0:
                return i

        i += 1

    die(f"unterminated {open_char}{close_char} block")


def split_top_level(text: str, delimiter: str = ",") -> list[str]:
    parts: list[str] = []
    start = 0
    paren_depth = 0
    brace_depth = 0
    bracket_depth = 0
    quote: str | None = None

    for index, ch in enumerate(text):
        if quote is not None:
            if ch == "\\":
                continue
            if ch == quote:
                quote = None
            continue

        if ch in {'"', "'"}:
            quote = ch
            continue

        if ch == "(":
            paren_depth += 1
            continue
        if ch == ")":
            paren_depth -= 1
            continue
        if ch == "{":
            brace_depth += 1
            continue
        if ch == "}":
            brace_depth -= 1
            continue
        if ch == "[":
            bracket_depth += 1
            continue
        if ch == "]":
            bracket_depth -= 1
            continue

        if ch == delimiter and paren_depth == 0 and brace_depth == 0 and bracket_depth == 0:
            part = text[start:index].strip()
            if part:
                parts.append(part)
            start = index + 1

    tail = text[start:].strip()
    if tail:
        parts.append(tail)
    return parts


def parse_designated_fields(body: str) -> dict[str, str]:
    fields: dict[str, str] = {}
    for part in split_top_level(body):
        if "=" not in part:
            continue
        field, value = part.split("=", 1)
        fields[field.strip()] = value.strip()
    return fields


def parse_macro_table(text: str, macro_name: str, invocation_name: str) -> list[list[str]]:
    lines = text.splitlines()
    start_index: int | None = None
    buffer: list[str] = []

    for index, line in enumerate(lines):
        if line.lstrip().startswith(f"#define {macro_name}("):
            start_index = index
            break

    if start_index is None:
        die(f"could not find macro block {macro_name}")

    for line in lines[start_index:]:
        buffer.append(line.rstrip())
        if not line.rstrip().endswith("\\"):
            break

    joined = "\n".join(buffer)
    joined = joined.split(")", 1)[1]
    body = joined.replace("\\\n", "\n")

    rows: list[list[str]] = []
    search = 0
    token = f"{invocation_name}("

    while True:
        start = body.find(token, search)
        if start == -1:
            break
        args_start = start + len(invocation_name)
        args_end = find_matching(body, args_start, "(", ")")
        inner = body[args_start + 1 : args_end]
        rows.append([normalize_expr(part) for part in split_top_level(inner)])
        search = args_end + 1

    return rows


def extract_initializer_body(text: str, pattern: str) -> str:
    match = re.search(pattern, text)
    if not match:
        die(f"could not find initializer for pattern: {pattern}")
    brace_start = text.find("{", match.end())
    if brace_start == -1:
        die(f"could not find opening brace for pattern: {pattern}")
    brace_end = find_matching(text, brace_start, "{", "}")
    return text[brace_start + 1 : brace_end]


def parse_keymap_custom_keycodes(text: str) -> list[str]:
    match = re.search(r"enum\s+keymap_custom_keycodes\s*\{(?P<body>.*?)\};", text, re.DOTALL)
    if not match:
        die("could not find enum keymap_custom_keycodes")

    keycodes: list[str] = []
    for entry in split_top_level(match.group("body")):
        token = entry.split("=", 1)[0].strip()
        if not token or token == "KEYMAP_CUSTOM_KEYCODE_SENTINEL":
            continue
        keycodes.append(token)
    return keycodes


def parse_config_layers(text: str) -> list[str]:
    match = re.search(r"enum\s+charybdis_keymap_layers\s*\{(?P<body>.*?)\};", text, re.DOTALL)
    if not match:
        die("could not find enum charybdis_keymap_layers")

    layers: list[str] = []
    for entry in split_top_level(match.group("body")):
        token = entry.split("=", 1)[0].strip()
        if not token or token == "LAYER_COUNT":
            continue
        layers.append(token)
    return layers


def parse_config_macros(text: str, names: list[str]) -> dict[str, str]:
    values: dict[str, str] = {}
    for name in names:
        match = re.search(rf"^\s*#\s*define\s+{re.escape(name)}\s+(.+?)\s*$", text, re.MULTILINE)
        if match:
            values[name] = normalize_expr(match.group(1))
    return values


def eval_numeric_expr(expr: str, known_values: dict[str, str]) -> int:
    normalized = normalize_expr(expr)
    if normalized in known_values:
        normalized = known_values[normalized]

    class ValueResolver(ast.NodeTransformer):
        def visit_Name(self, node: ast.Name) -> ast.AST:
            if node.id not in known_values:
                die(f"unknown numeric identifier in expression: {expr!r}")
            return ast.copy_location(ast.Constant(value=eval_numeric_expr(known_values[node.id], known_values)), node)

    try:
        tree = ast.parse(normalized, mode="eval")
    except SyntaxError as exc:
        die(f"could not parse numeric expression {expr!r}: {exc}")

    tree = ValueResolver().visit(tree)
    ast.fix_missing_locations(tree)

    def _eval(node: ast.AST) -> int:
        if isinstance(node, ast.Expression):
            return _eval(node.body)
        if isinstance(node, ast.Constant) and isinstance(node.value, (int, float)):
            return int(round(node.value))
        if isinstance(node, ast.UnaryOp) and isinstance(node.op, (ast.UAdd, ast.USub)):
            value = _eval(node.operand)
            return value if isinstance(node.op, ast.UAdd) else -value
        if isinstance(node, ast.BinOp) and isinstance(node.op, (ast.Add, ast.Sub, ast.Mult, ast.Div, ast.FloorDiv)):
            left = _eval(node.left)
            right = _eval(node.right)
            if isinstance(node.op, ast.Add):
                return left + right
            if isinstance(node.op, ast.Sub):
                return left - right
            if isinstance(node.op, ast.Mult):
                return left * right
            if right == 0:
                die(f"division by zero in expression: {expr!r}")
            return left // right
        die(f"unsupported numeric expression: {expr!r}")

    return _eval(tree)


def parse_hsv_expr(expr: str, known_values: dict[str, str]) -> dict[str, object]:
    normalized = normalize_expr(expr)
    if not normalized.startswith("HSV(") or not normalized.endswith(")"):
        die(f"expected HSV(...) color expression, got: {expr!r}")
    parts = split_top_level(normalized[4:-1])
    if len(parts) != 3:
        die(f"HSV(...) expected 3 arguments, got: {expr!r}")
    h = eval_numeric_expr(parts[0], known_values)
    s = eval_numeric_expr(parts[1], known_values)
    v = eval_numeric_expr(parts[2], known_values)
    return {"h": h, "s": s, "v": v, "hex": hsv_to_hex(h, s, v), "enabled": not (h == 0 and s == 0 and v == 0)}


def hsv_to_hex(h: int, s: int, v: int) -> str:
    r, g, b = colorsys.hsv_to_rgb((h % 256) / 255.0, max(0, min(s, 255)) / 255.0, max(0, min(v, 255)) / 255.0)
    return "#{:02x}{:02x}{:02x}".format(int(round(r * 255)), int(round(g * 255)), int(round(b * 255)))


def parse_layer_colors(text: str, known_values: dict[str, str]) -> list[dict[str, object]]:
    body = extract_initializer_body(text, r"layer_colors\[LAYER_COUNT\]\s*=")
    colors: list[dict[str, object]] = []

    for entry in split_top_level(body):
        if "=" not in entry:
            continue
        layer_expr, body_expr = entry.split("=", 1)
        layer_match = re.search(r"\[(?P<name>[A-Z_][A-Z0-9_]*)\]", layer_expr)
        if layer_match is None:
            die(f"could not parse layer color entry: {entry!r}")
        layer_name = layer_match.group("name")
        body_expr = body_expr.strip()
        if not (body_expr.startswith("{") and body_expr.endswith("}")):
            die(f"unexpected layer color body: {body_expr!r}")
        fields = parse_designated_fields(body_expr[1:-1].strip())
        colors.append(
            {
                "layer": layer_name,
                "color": parse_hsv_expr(fields[".color"], known_values),
                "mode": normalize_expr(fields[".mode"]),
            }
        )

    if not colors:
        die("no layer colors parsed from rgb_config.c")

    return colors


def resolve_rgb_default_color(known_values: dict[str, str]) -> dict[str, object]:
    return {
        "h": eval_numeric_expr(known_values["RGB_MATRIX_DEFAULT_HUE"], known_values),
        "s": eval_numeric_expr(known_values["RGB_MATRIX_DEFAULT_SAT"], known_values),
        "v": eval_numeric_expr(known_values["RGB_MATRIX_DEFAULT_VAL"], known_values),
        "hex": hsv_to_hex(
            eval_numeric_expr(known_values["RGB_MATRIX_DEFAULT_HUE"], known_values),
            eval_numeric_expr(known_values["RGB_MATRIX_DEFAULT_SAT"], known_values),
            eval_numeric_expr(known_values["RGB_MATRIX_DEFAULT_VAL"], known_values),
        ),
        "enabled": True,
    }


def finalize_layer_colors(layer_colors: list[dict[str, object]], rgb_default_color: dict[str, object]) -> list[dict[str, object]]:
    finalized: list[dict[str, object]] = []

    for row in layer_colors:
        color = row["color"]
        if row["layer"] == "LAYER_BASE" and not color["enabled"]:
            preview_color = dict(rgb_default_color)
            preview_source = "rgb_default"
        elif color["enabled"]:
            preview_color = dict(color)
            preview_source = "layer_override"
        else:
            preview_color = None
            preview_source = "no_override"

        finalized.append({**row, "preview_color": preview_color, "preview_source": preview_source})

    return finalized


def parse_pd_modes(text: str) -> list[dict[str, str]]:
    modes: list[dict[str, str]] = []
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line.startswith("PDM("):
            continue
        match = _PD_MODE_MANIFEST_ENTRY_PATTERN.match(line)
        if not match:
            die(f"could not parse pd-mode manifest row: {raw_line!r}")
        name, keycode = match.groups()
        modes.append({"name": name, "keycode": keycode})
    return modes


def parse_macro_slots(rows: list[list[str]], kind: str) -> list[MacroSlot]:
    slots: list[MacroSlot] = []
    for row in rows:
        if len(row) != 2:
            die(f"expected 2 arguments in {kind} macro row, got: {row!r}")
        keycode, payload = row
        normalized_payload = payload.strip()
        if normalized_payload.startswith('"') and normalized_payload.endswith('"'):
            normalized_payload = normalized_payload[1:-1]
        slot_match = re.search(r"_(\d+)$", keycode)
        if slot_match is None:
            die(f"could not determine slot for macro keycode: {keycode}")
        slots.append(
            MacroSlot(
                kind=kind,
                slot=int(slot_match.group(1)),
                keycode=keycode,
                payload=normalized_payload,
                empty=normalized_payload == "",
            )
        )
    return slots


def parse_key_behaviors(text: str) -> list[KeyBehavior]:
    body = extract_initializer_body(text, r"key_behaviors\[\]\s*=")
    behaviors: list[KeyBehavior] = []

    for entry in split_top_level(body):
        if not entry.startswith("{") or not entry.endswith("}"):
            die(f"unexpected key behavior entry: {entry!r}")
        fields = parse_designated_fields(entry[1:-1].strip())
        keycode = normalize_expr(fields[".keycode"])
        tap_counts_body = fields.get(".tap_counts", "{}")
        steps = parse_behavior_steps(tap_counts_body)
        behaviors.append(
            KeyBehavior(
                keycode=keycode,
                tap_hold_term=parse_optional_int(fields.get(".tap_hold_term")),
                longer_hold_term=parse_optional_int(fields.get(".longer_hold_term")),
                multi_tap_term=parse_optional_int(fields.get(".multi_tap_term")),
                steps=steps,
            )
        )

    return behaviors


def parse_optional_int(value: str | None) -> int | None:
    if value is None:
        return None
    normalized = normalize_expr(value)
    if not normalized:
        return None
    try:
        return int(normalized, 10)
    except ValueError:
        return None


def parse_behavior_steps(tap_counts_body: str) -> list[BehaviorStep]:
    normalized = tap_counts_body.strip()
    if not (normalized.startswith("{") and normalized.endswith("}")):
        die(f"unexpected tap_counts initializer: {tap_counts_body!r}")

    steps: list[BehaviorStep] = []
    inner = normalized[1:-1].strip()
    if not inner:
        return steps

    for entry in split_top_level(inner):
        if "=" not in entry:
            continue
        index_expr, body_expr = entry.split("=", 1)
        index_match = re.search(r"\[(\d+)\]", index_expr)
        if index_match is None:
            die(f"could not parse tap count index from: {entry!r}")
        tap_count = int(index_match.group(1))
        body_expr = body_expr.strip()
        if not (body_expr.startswith("{") and body_expr.endswith("}")):
            die(f"unexpected behavior step body: {body_expr!r}")
        fields = parse_designated_fields(body_expr[1:-1].strip())
        steps.append(
            BehaviorStep(
                tap_count=tap_count,
                tap=parse_behavior_action(fields.get(".tap")),
                hold=parse_behavior_action(fields.get(".hold")),
                long_hold=parse_behavior_action(fields.get(".long_hold")),
            )
        )

    return steps


def parse_behavior_action(value: str | None) -> BehaviorAction | None:
    if value is None:
        return None
    normalized = normalize_expr(value)
    if not normalized:
        return None
    open_index = normalized.find("(")
    if open_index == -1 or not normalized.endswith(")"):
        die(f"unexpected behavior helper expression: {value!r}")
    helper = normalized[:open_index]
    inner = normalized[open_index + 1 : -1]
    args = split_top_level(inner)

    if helper == "REPEAT_WHILE_HELD":
        if len(args) != 2:
            die(f"REPEAT_WHILE_HELD expected 2 args, got {args!r}")
        return BehaviorAction(helper=helper, action=normalize_expr(args[0]), repeat_hz=int(normalize_expr(args[1]), 10))

    if len(args) != 1:
        die(f"{helper} expected 1 arg, got {args!r}")
    return BehaviorAction(helper=helper, action=normalize_expr(args[0]))


def parse_combos(text: str) -> list[Combo]:
    combos: list[Combo] = []
    for row in parse_macro_table(text, "COMBOS", "COMBO"):
        if len(row) != 2:
            die(f"unexpected combo row: {row!r}")
        output, inputs_expr = row
        normalized_inputs = inputs_expr.strip()
        if normalized_inputs.startswith("(") and normalized_inputs.endswith(")"):
            normalized_inputs = normalized_inputs[1:-1]
        inputs = [normalize_expr(item) for item in split_top_level(normalized_inputs)]
        combos.append(Combo(output=output, inputs=inputs))
    return combos


def parse_layers(text: str, known_behaviors: set[str]) -> list[dict[str, object]]:
    array_body = extract_initializer_body(text, r"keymaps\[\]\[MATRIX_ROWS\]\[MATRIX_COLS\]\s*=")
    layers: list[dict[str, object]] = []
    search = 0

    while True:
        match = re.search(r"\[(?P<name>[A-Z_][A-Z0-9_]*)\]\s*=\s*LAYOUT\s*\(", array_body[search:])
        if not match:
            break
        layer_name = match.group("name")
        absolute_start = search + match.start()
        open_paren = array_body.find("(", absolute_start)
        close_paren = find_matching(array_body, open_paren, "(", ")")
        items = [normalize_expr(item) for item in split_top_level(array_body[open_paren + 1 : close_paren])]
        if len(items) != len(LAYOUT_TEMPLATE):
            die(f"{layer_name} expected {len(LAYOUT_TEMPLATE)} layout entries, got {len(items)}")
        positions: list[dict[str, object]] = []
        for layout_index, (template, keycode) in enumerate(zip(LAYOUT_TEMPLATE, items, strict=True)):
            positions.append(
                {
                    "layout_index": layout_index,
                    "matrix": template["matrix"],
                    "x": template["x"],
                    "y": template["y"],
                    "keycode": keycode,
                    "display": display_token(keycode),
                    "has_key_behavior": keycode in known_behaviors,
                }
            )
        layers.append({"name": layer_name, "positions": positions})
        search = close_paren + 1

    if not layers:
        die("no layers parsed from keymaps[][]")
    return layers


def short_layer_name(name: str) -> str:
    return name.removeprefix("LAYER_")


def short_mode_name(name: str) -> str:
    return name.removesuffix("_MODE")


def display_token(token: str) -> str:
    normalized = normalize_expr(token)
    if normalized in DISPLAY_ALIASES:
        return DISPLAY_ALIASES[normalized]
    if normalized.startswith("VIA_MACRO_"):
        return "VIA" + normalized.rsplit("_", 1)[1]
    if normalized.startswith("MACRO_"):
        return "MACRO" + normalized.rsplit("_", 1)[1]
    if normalized.startswith("KC_"):
        return normalized[3:]
    if normalized.startswith("LT(") and normalized.endswith(")"):
        inner = split_top_level(normalized[3:-1])
        if len(inner) == 2:
            inner_label = display_token(inner[1])
            if inner_label == "/":
                inner_label = "SLSH"
            return f"LT[{short_layer_name(inner[0])}]/{inner_label}"
    if normalized.startswith("MO(") and normalized.endswith(")"):
        return f"MO[{short_layer_name(normalized[3:-1])}]"
    if normalized.startswith("LOCK_LAYER(") and normalized.endswith(")"):
        return f"LOCK[{short_layer_name(normalized[11:-1])}]"
    if normalized.startswith("LOCK_PD_MODE(") and normalized.endswith(")"):
        return f"LOCK[{short_mode_name(normalized[13:-1])}]"
    if normalized.startswith("S(") and normalized.endswith(")"):
        return f"S({display_token(normalized[2:-1])})"
    if normalized.startswith("A(") and normalized.endswith(")"):
        return f"A({display_token(normalized[2:-1])})"
    if normalized.startswith("G(") and normalized.endswith(")"):
        return f"G({display_token(normalized[2:-1])})"
    if normalized.startswith("LAG(") and normalized.endswith(")"):
        return f"LAG({display_token(normalized[4:-1])})"
    if normalized.startswith("LSG(") and normalized.endswith(")"):
        return f"LSG({display_token(normalized[4:-1])})"
    if normalized.startswith("LCAG(") and normalized.endswith(")"):
        return f"LCAG({display_token(normalized[5:-1])})"
    if normalized.endswith("_MODE"):
        return short_mode_name(normalized)
    return normalized


def collect_macro_usages(
    layers: list[dict[str, object]],
    behaviors: list[KeyBehavior],
    combos: list[Combo],
    macros: list[MacroSlot],
) -> dict[str, list[dict[str, object]]]:
    usage_map = {macro.keycode: [] for macro in macros}

    for layer in layers:
        layer_name = layer["name"]
        for position in layer["positions"]:
            keycode = position["keycode"]
            if keycode in usage_map:
                usage_map[keycode].append(
                    {
                        "kind": "layer",
                        "layer": layer_name,
                        "layout_index": position["layout_index"],
                        "matrix": position["matrix"],
                    }
                )

    for behavior in behaviors:
        for step in behavior.steps:
            for field_name in ("tap", "hold", "long_hold"):
                action = getattr(step, field_name)
                if action is None or action.action not in usage_map:
                    continue
                usage_map[action.action].append(
                    {
                        "kind": "behavior",
                        "owner": behavior.keycode,
                        "tap_count": step.tap_count,
                        "field": field_name,
                    }
                )

    for index, combo in enumerate(combos):
        if combo.output in usage_map:
            usage_map[combo.output].append({"kind": "combo_output", "combo_index": index})
        for input_key in combo.inputs:
            if input_key in usage_map:
                usage_map[input_key].append({"kind": "combo_input", "combo_index": index})

    return usage_map


def build_profile_model() -> dict[str, object]:
    config_text = strip_comments(read_text(CONFIG_FILE))
    rgb_config_text = strip_comments(read_text(RGB_CONFIG_FILE))
    keymap_text = strip_comments(read_text(KEYMAP_FILE))
    noah_ids_text = strip_comments(read_text(NOAH_KEYMAP_IDS_FILE))
    pd_mode_text = strip_comments(read_text(PD_MODE_MANIFEST_FILE))

    layers = parse_config_layers(config_text)
    config_macros = parse_config_macros(config_text, CONFIG_MACROS)
    layer_colors = finalize_layer_colors(parse_layer_colors(rgb_config_text, config_macros), resolve_rgb_default_color(config_macros))
    keymap_custom_keycodes = parse_keymap_custom_keycodes(keymap_text)
    via_macros = parse_macro_slots(parse_macro_table(keymap_text, "VIA_MACROS", "MACRO"), kind="via")
    hardcoded_macros = parse_macro_slots(parse_macro_table(keymap_text, "HARDCODED_MACROS", "MACRO"), kind="hardcoded")
    behaviors = parse_key_behaviors(keymap_text)
    combos = parse_combos(keymap_text)
    parsed_layers = parse_layers(keymap_text, known_behaviors={behavior.keycode for behavior in behaviors})
    pd_modes = parse_pd_modes(pd_mode_text)

    macro_usages = collect_macro_usages(parsed_layers, behaviors, combos, via_macros + hardcoded_macros)

    via_slots = []
    for slot in via_macros:
        via_slots.append({**asdict(slot), "usages": macro_usages[slot.keycode]})

    hardcoded_slots = []
    for slot in hardcoded_macros:
        hardcoded_slots.append({**asdict(slot), "usages": macro_usages[slot.keycode]})

    layer_lock_match = re.search(r"#\s*define\s+LOCK_LAYER\(layer_\)\s+\((.+)\)", noah_ids_text)
    lock_layer_expr = normalize_expr(layer_lock_match.group(1)) if layer_lock_match else ""
    pd_lock_match = re.search(r"#\s*define\s+LOCK_PD_MODE\(mode_keycode_\)\s+(.+)", noah_ids_text)
    lock_pd_expr = normalize_expr(pd_lock_match.group(1)) if pd_lock_match else ""

    behavior_rows = [asdict(behavior) for behavior in behaviors]
    combos_rows = [asdict(combo) for combo in combos]

    summary = {
        "layer_count": len(parsed_layers),
        "layout_key_count": len(LAYOUT_TEMPLATE),
        "key_behavior_count": len(behaviors),
        "key_behavior_step_count": sum(len(behavior.steps) for behavior in behaviors),
        "combo_count": len(combos),
        "via_macro_count": len(via_macros),
        "via_macro_non_empty_count": sum(not slot.empty for slot in via_macros),
        "hardcoded_macro_count": len(hardcoded_macros),
        "hardcoded_macro_non_empty_count": sum(not slot.empty for slot in hardcoded_macros),
        "keymap_custom_keycode_count": len(keymap_custom_keycodes),
        "pd_mode_count": len(pd_modes),
    }

    return {
        "summary": summary,
        "config": {"layers": layers, "macros": config_macros},
        "rgb": {"layer_colors": layer_colors},
        "derived_keycode_rules": {
            "lock_layer": lock_layer_expr,
            "lock_pd_mode": lock_pd_expr,
        },
        "pd_modes": pd_modes,
        "keymap_custom_keycodes": keymap_custom_keycodes,
        "via_macros": via_slots,
        "hardcoded_macros": hardcoded_slots,
        "combos": combos_rows,
        "key_behaviors": behavior_rows,
        "layers": parsed_layers,
    }


def render_markdown(profile: dict[str, object]) -> str:
    sections = [
        MARKDOWN_HEADER.rstrip(),
        "# Profile Introspection",
        "",
        "This report is generated from the authored profile data in `keymap.c`, `config.h`, `noah_keymap_ids.h`, and the pd-mode manifest.",
        "",
        render_summary_section(profile),
        render_layer_maps_section(profile),
        render_key_behavior_section(profile),
        render_combo_section(profile),
        render_macro_section(profile),
        render_json_section(),
    ]
    return "\n".join(section for section in sections if section)


def render_summary_section(profile: dict[str, object]) -> str:
    summary = profile["summary"]
    config = profile["config"]
    rgb = profile["rgb"]
    lines = [
        "## Summary",
        "",
        "| Field | Value |",
        "| --- | --- |",
    ]
    for key, value in summary.items():
        lines.append(f"| `{key}` | `{value}` |")

    lines.extend(
        [
            "",
            "### Keymap Config",
            "",
            "| Macro | Value |",
            "| --- | --- |",
        ]
    )
    for name, value in config["macros"].items():
        lines.append(f"| `{name}` | `{value}` |")

    lines.extend(
        [
            "",
            "### Layer RGB Config",
            "",
            "| Layer | Mode | Authored HSV | Preview Color | Source |",
            "| --- | --- | --- | --- | --- |",
        ]
    )
    for row in rgb["layer_colors"]:
        color = row["color"]
        preview_color = row["preview_color"]
        preview_label = preview_color["hex"] if preview_color is not None else "no override"
        source_label = {
            "layer_override": "layer override",
            "rgb_default": "RGB default",
            "no_override": "no override",
        }[row["preview_source"]]
        lines.append(
            f"| `{row['layer']}` | `{row['mode']}` | `HSV({color['h']}, {color['s']}, {color['v']})` | `{preview_label}` | `{source_label}` |"
        )

    lines.extend(
        [
            "",
            "### Shared Keycode Surfaces",
            "",
            f"- Layers: {', '.join(f'`{layer}`' for layer in config['layers'])}",
            f"- Keymap-local custom keycodes: {', '.join(f'`{name}`' for name in profile['keymap_custom_keycodes']) or '`none`'}",
            f"- PD modes: {', '.join(f'`{mode['keycode']}`' for mode in profile['pd_modes']) or '`none`'}",
            "",
        ]
    )
    return "\n".join(lines)


def render_layer_maps_section(profile: dict[str, object]) -> str:
    layer_color_map = {row["layer"]: row for row in profile["rgb"]["layer_colors"]}
    lines = [
        "## Layer Images",
        "",
        "These previews are generated as SVG image assets in this folder. The renderer uses the authored `layer_colors[]` config from `rgb_config.c`:",
        "",
        "- `ALL_KEYS`: tint every physical key with the layer color",
        "- `KEYS_MAPPED_ON_THIS_LAYER_ONLY`: tint only non-`TRNS`, non-`NO` positions and dim the rest",
        "- `LAYER_BASE` falls back to the default RGB color from `config.h` when its authored layer color is `HSV(0, 0, 0)`",
        "",
    ]
    for layer in profile["layers"]:
        color_config = layer_color_map[layer["name"]]
        image_name = layer_image_name(layer["name"])
        preview_color = color_config["preview_color"]
        color_label = preview_color["hex"] if preview_color is not None else "no override"
        source_label = {
            "layer_override": "layer override",
            "rgb_default": "RGB default from config.h",
            "no_override": "no color override",
        }[color_config["preview_source"]]
        lines.append(f"### `{layer['name']}`")
        lines.append("")
        lines.append(f"- Render mode: `{color_config['mode']}`")
        lines.append(f"- Authored layer color: `HSV({color_config['color']['h']}, {color_config['color']['s']}, {color_config['color']['v']})`")
        lines.append(f"- Preview color source: `{source_label}` -> `{color_label}`")
        lines.append("")
        lines.append(f"![{layer['name']}](./{image_name})")
        lines.append("")
    return "\n".join(lines)

def layer_image_name(layer_name: str) -> str:
    return f"{LAYER_IMAGE_PREFIX}{layer_name}.svg"


def build_generated_assets(profile: dict[str, object]) -> dict[Path, str]:
    markdown = render_markdown(profile)
    json_text = render_json(profile)
    assets: dict[Path, str] = {
        MARKDOWN_OUTPUT: markdown,
        JSON_OUTPUT: json_text,
    }

    layer_color_map = {row["layer"]: row for row in profile["rgb"]["layer_colors"]}
    for layer in profile["layers"]:
        image_path = OUTPUT_DIR / layer_image_name(layer["name"])
        assets[image_path] = render_layer_svg(layer, layer_color_map[layer["name"]])

    return assets


def render_layer_svg(layer: dict[str, object], color_config: dict[str, object]) -> str:
    parts = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{SVG_CANVAS_WIDTH}" height="{SVG_CANVAS_HEIGHT}" viewBox="0 0 {SVG_CANVAS_WIDTH} {SVG_CANVAS_HEIGHT}" role="img" aria-labelledby="title desc">',
        f"  <title id=\"title\">{layer['name']} layout preview</title>",
        f"  <desc id=\"desc\">Generated layer preview for {layer['name']} using authored RGB layer color and mapped-key render mode.</desc>",
        "  <defs>",
        "    <filter id=\"shadow\" x=\"-20%\" y=\"-20%\" width=\"140%\" height=\"140%\">",
        "      <feDropShadow dx=\"0\" dy=\"5\" stdDeviation=\"4\" flood-color=\"#000000\" flood-opacity=\"0.22\"/>",
        "    </filter>",
        "  </defs>",
        f"  <rect width=\"{SVG_CANVAS_WIDTH}\" height=\"{SVG_CANVAS_HEIGHT}\" fill=\"{SVG_BACKGROUND}\"/>",
        f"  <text x=\"{TITLE_X}\" y=\"{TITLE_Y}\" fill=\"#f5f5f3\" font-size=\"26\" font-family=\"Helvetica, Arial, sans-serif\" font-weight=\"700\">{layer['name']}</text>",
        f"  <text x=\"{TITLE_X}\" y=\"{SUBTITLE_Y}\" fill=\"#cfcfcb\" font-size=\"14\" font-family=\"Helvetica, Arial, sans-serif\">{svg_subtitle(color_config)}</text>",
    ]

    for position in layer["positions"]:
        geometry = visual_geometry(position)
        style = layer_key_style(position, color_config)
        label = visual_label_for_position(position, style["variant"])
        parts.extend(render_svg_key(geometry, label, style))

    parts.append("</svg>")
    return "\n".join(parts) + "\n"


def svg_subtitle(color_config: dict[str, object]) -> str:
    color = color_config["color"]
    preview_color = color_config["preview_color"]
    if color_config["preview_source"] == "rgb_default" and preview_color is not None:
        return (
            f"{color_config['mode']} • authored HSV({color['h']}, {color['s']}, {color['v']}) "
            f"• RGB default {preview_color['hex']}"
        )
    if preview_color is not None:
        return f"{color_config['mode']} • HSV({color['h']}, {color['s']}, {color['v']}) • {preview_color['hex']}"
    return f"{color_config['mode']} • HSV({color['h']}, {color['s']}, {color['v']}) • no layer wash"


def visual_geometry(position: dict[str, object]) -> dict[str, float]:
    layout_index = position["layout_index"]
    matrix_row, matrix_col = position["matrix"]

    if layout_index in THUMB_VISUALS:
        thumb = THUMB_VISUALS[layout_index]
        return {"x": thumb["x"], "y": thumb["y"] + KEYBOARD_Y_OFFSET, "angle": thumb["angle"]}

    if matrix_row <= 3:
        return {
            "x": LEFT_COLUMN_X[matrix_col],
            "y": LEFT_COLUMN_TOP_Y[matrix_col] + (matrix_row * ROW_Y_STEP) + KEYBOARD_Y_OFFSET,
            "angle": 0,
        }

    physical_row = matrix_row - 5
    physical_col = 5 - matrix_col
    return {
        "x": RIGHT_COLUMN_X[physical_col],
        "y": RIGHT_COLUMN_TOP_Y[physical_col] + (physical_row * ROW_Y_STEP) + KEYBOARD_Y_OFFSET,
        "angle": 0,
    }


def layer_key_style(position: dict[str, object], color_config: dict[str, object]) -> dict[str, object]:
    keycode = position["keycode"]
    is_transparent = keycode == "_______"
    is_none = keycode == "XXXXXXX"
    has_real_mapping = not is_transparent and not is_none
    preview_color = color_config["preview_color"]
    preview_enabled = preview_color is not None and preview_color["v"] > 0
    tint_all = color_config["mode"] == "ALL_KEYS" and preview_enabled
    tint_mapped = color_config["mode"] == "KEYS_MAPPED_ON_THIS_LAYER_ONLY" and has_real_mapping and preview_enabled
    tint = tint_all or tint_mapped

    if tint:
        fill = preview_color["hex"]
        text = ideal_text_color(fill)
        return {"fill": fill, "text": text, "stroke": adjust_hex(fill, -28), "label_opacity": 1.0, "variant": "mapped"}

    if is_transparent or is_none:
        return {"fill": "#c9cac5", "text": "#444744", "stroke": "#a8aaa5", "label_opacity": 0.0, "variant": "dimmed"}

    return {"fill": "#f4f4f1", "text": "#1f221f", "stroke": "#d2d3ce", "label_opacity": 1.0, "variant": "neutral"}


def visual_label_for_position(position: dict[str, object], variant: str) -> str:
    if variant == "dimmed":
        return ""
    return position["display"]


def render_svg_key(geometry: dict[str, float], label: str, style: dict[str, object]) -> list[str]:
    x = geometry["x"]
    y = geometry["y"]
    angle = geometry["angle"]
    cx = x + (KEY_WIDTH / 2)
    cy = y + (KEY_HEIGHT / 2)
    parts = [f'  <g transform="rotate({angle} {cx:.1f} {cy:.1f})">']
    parts.append(
        f'    <rect x="{x:.1f}" y="{y:.1f}" width="{KEY_WIDTH}" height="{KEY_HEIGHT}" rx="{KEY_RADIUS}" fill="{style["fill"]}" stroke="{style["stroke"]}" stroke-width="1.5" filter="url(#shadow)"/>'
    )
    if label:
        font_size = 12 if len(label) <= 5 else 11 if len(label) <= 8 else 9
        parts.append(
            f'    <text x="{cx:.1f}" y="{cy + 4:.1f}" fill="{style["text"]}" fill-opacity="{style["label_opacity"]}" font-size="{font_size}" text-anchor="middle" font-family="Helvetica, Arial, sans-serif" font-weight="600">{escape_xml(label)}</text>'
        )
    parts.append("  </g>")
    return parts


def escape_xml(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")


def ideal_text_color(fill_hex: str) -> str:
    red = int(fill_hex[1:3], 16)
    green = int(fill_hex[3:5], 16)
    blue = int(fill_hex[5:7], 16)
    luminance = ((0.299 * red) + (0.587 * green) + (0.114 * blue)) / 255.0
    return "#1c1f1c" if luminance > 0.6 else "#f7f7f4"


def adjust_hex(fill_hex: str, delta: int) -> str:
    red = max(0, min(255, int(fill_hex[1:3], 16) + delta))
    green = max(0, min(255, int(fill_hex[3:5], 16) + delta))
    blue = max(0, min(255, int(fill_hex[5:7], 16) + delta))
    return "#{:02x}{:02x}{:02x}".format(red, green, blue)


def render_key_behavior_section(profile: dict[str, object]) -> str:
    lines = [
        "## Key Behavior Inventory",
        "",
        "| Keycode | Tap Count | Tap | Hold | Long Hold | Timing |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for behavior in profile["key_behaviors"]:
        timing = format_timing(behavior)
        for step in behavior["steps"]:
            lines.append(
                "| `{keycode}` | `{tap_count}` | `{tap}` | `{hold}` | `{long_hold}` | `{timing}` |".format(
                    keycode=behavior["keycode"],
                    tap_count=TAP_COUNT_NAMES.get(step["tap_count"], str(step["tap_count"])),
                    tap=format_behavior_action(step["tap"]),
                    hold=format_behavior_action(step["hold"]),
                    long_hold=format_behavior_action(step["long_hold"]),
                    timing=timing,
                )
            )
    lines.append("")
    return "\n".join(lines)


def format_timing(behavior: dict[str, object]) -> str:
    parts = []
    if behavior["tap_hold_term"] is not None:
        parts.append(f"tap_hold={behavior['tap_hold_term']}")
    if behavior["longer_hold_term"] is not None:
        parts.append(f"long_hold={behavior['longer_hold_term']}")
    if behavior["multi_tap_term"] is not None:
        parts.append(f"multi_tap={behavior['multi_tap_term']}")
    return ", ".join(parts) if parts else "defaults"


def format_behavior_action(action: dict[str, object] | None) -> str:
    if action is None:
        return "-"
    helper = action["helper"]
    if action["repeat_hz"] is not None:
        return f"{helper}({action['action']}, {action['repeat_hz']}Hz)"
    return f"{helper}({action['action']})"


def render_combo_section(profile: dict[str, object]) -> str:
    lines = [
        "## Combos",
        "",
        "| Inputs | Output |",
        "| --- | --- |",
    ]
    for combo in profile["combos"]:
        inputs = ", ".join(f"`{item}`" for item in combo["inputs"])
        lines.append(f"| {inputs} | `{combo['output']}` |")

    lines.extend(["", "### Combo Graph", "", "```mermaid", "flowchart LR"])
    for index, combo in enumerate(profile["combos"]):
        combo_id = f"combo_{index}"
        lines.append(f'    {combo_id}["Combo {index + 1}"]')
        lines.append(f'    {combo_id}_out["{escape_mermaid_label(combo["output"])}"]')
        lines.append(f"    {combo_id} --> {combo_id}_out")
        for input_index, keycode in enumerate(combo["inputs"]):
            input_id = f"{combo_id}_in_{input_index}"
            lines.append(f'    {input_id}["{escape_mermaid_label(keycode)}"]')
            lines.append(f"    {input_id} --> {combo_id}")
    lines.extend(["```", ""])
    return "\n".join(lines)


def escape_mermaid_label(label: str) -> str:
    return label.replace('"', '\\"')


def render_macro_section(profile: dict[str, object]) -> str:
    lines = [
        "## Macro Inventory",
        "",
        "### VIA Macros",
        "",
        "| Slot | Payload | Usage |",
        "| --- | --- | --- |",
    ]
    for slot in profile["via_macros"]:
        lines.append(f"| `{slot['keycode']}` | `{slot['payload'] or '<empty>'}` | {format_usages(slot['usages'])} |")

    lines.extend(["", "### Hardcoded Macros", "", "| Slot | Payload | Usage |", "| --- | --- | --- |"])
    for slot in profile["hardcoded_macros"]:
        lines.append(f"| `{slot['keycode']}` | `{slot['payload'] or '<empty>'}` | {format_usages(slot['usages'])} |")
    lines.append("")
    return "\n".join(lines)


def format_usages(usages: list[dict[str, object]]) -> str:
    if not usages:
        return "-"
    labels: list[str] = []
    for usage in usages:
        kind = usage["kind"]
        if kind == "layer":
            matrix = usage["matrix"]
            labels.append(f"`{usage['layer']} @ matrix[{matrix[0]},{matrix[1]}]`")
        elif kind == "behavior":
            tap_count = TAP_COUNT_NAMES.get(usage["tap_count"], str(usage["tap_count"]))
            labels.append(f"`{usage['owner']} {tap_count} {usage['field']}`")
        elif kind == "combo_output":
            labels.append(f"`combo {usage['combo_index'] + 1} output`")
        elif kind == "combo_input":
            labels.append(f"`combo {usage['combo_index'] + 1} input`")
    return ", ".join(labels)


def render_json_section() -> str:
    return "\n".join(
        [
            "## Diffable JSON",
            "",
            f"- Generated artifact: [`{JSON_OUTPUT.relative_to(REPO_ROOT)}`](./profile-summary.json)",
            f"- Generated layer images: `./{LAYER_IMAGE_PREFIX}*.svg`",
            f"- Regenerate the report, JSON summary, and layer images with `python3 tools/profile_introspect.py --write`",
            f"- Verify they are current with `python3 tools/profile_introspect.py --check`",
            "",
        ]
    )


def render_json(profile: dict[str, object]) -> str:
    return json.dumps(profile, indent=2) + "\n"


def write_outputs(assets: dict[Path, str]) -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    for path, contents in assets.items():
        path.write_text(contents)


def check_outputs(assets: dict[Path, str]) -> int:
    failures: list[str] = []

    for path, expected in assets.items():
        if not path.exists():
            failures.append(f"missing generated file: {path}")
            continue
        actual = path.read_text()
        if actual != expected:
            diff = "".join(
                difflib.unified_diff(
                    actual.splitlines(keepends=True),
                    expected.splitlines(keepends=True),
                    fromfile=str(path),
                    tofile=f"{path} (expected)",
                )
            )
            failures.append(diff)

    if failures:
        for failure in failures:
            sys.stderr.write(failure)
            if not failure.endswith("\n"):
                sys.stderr.write("\n")
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="write docs/generated/profile-introspection.md and docs/generated/profile-summary.json")
    parser.add_argument("--check", action="store_true", help="fail if the generated artifacts are not current")
    parser.add_argument("--print-markdown", action="store_true", help="print the Markdown report to stdout")
    parser.add_argument("--print-json", action="store_true", help="print the JSON summary to stdout")
    args = parser.parse_args()

    if not any((args.write, args.check, args.print_markdown, args.print_json)):
        args.write = True

    profile = build_profile_model()
    assets = build_generated_assets(profile)
    markdown = assets[MARKDOWN_OUTPUT]
    json_text = assets[JSON_OUTPUT]

    if args.write:
        write_outputs(assets)

    if args.check:
        check_status = check_outputs(assets)
        if check_status != 0:
            return check_status

    if args.print_markdown:
        sys.stdout.write(markdown)

    if args.print_json:
        sys.stdout.write(json_text)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
