name: Build Binaries

on:
  workflow_call:
    inputs:
      release_name:
        description: "allow setting the release name"
        default: "latest"
        required: false
        type: string

permissions:
  contents: write

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: Firmware

      - name: Verify both halves are present
        run: |
          test -s bastardkb_charybdis_4x6_noah_left.uf2
          test -s bastardkb_charybdis_4x6_noah_right.uf2

      - name: Generate Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ github.token }}
          name: Charybdis 4x6 ${{ inputs.release_name }}
          tag_name: ${{ inputs.release_name || 'latest' }}
          fail_on_unmatched_files: true
          draft: false
          prerelease: false
          files: |
            bastardkb_charybdis_4x6_noah_left.uf2
            bastardkb_charybdis_4x6_noah_right.uf2
